### ISSUE TITLE
No error handling

### ISSUE THREAD

**Issue by rubenstolk** [intercom/intercom-node#134]
## Version info
  - intercom-node version: 2.8.5
  - Node version: 7.x

## Expected behavior
When making an invalid call, throw an error or call callback with error

## Actual behavior
Silence

## Steps to reproduce
 1. intercom.users.find({ some_attribute_other_than_id_or_email_or_user_id: 123 })

**Comment by choran** [comment]
Hi @rubenstolk 
I am just trying to review some old issues that we never got to. I see what you mean, i.e. it returns error if the user does not exist, but if you use an invalid attribute it fails silently?
Yeah, you would expect an error to be returned here, I think we do that in other SDKs.
Thanks, will leave this open so that we can track it as something we need to get to
Thanks for raising
Cathal

**Comment by choran** [comment]
Hi @rubenstolk 
Apologies for the delay here, we were reviewing some older node issues and I looked into this in a little more detail. It is actually an issue with our API. i.e. when you add an incorrect search parameter then the API defaults  to a find_all. So it is not actually an SDK issue. I will raise this internally as something we need to fix in our API as it is very confusing and I am sure it is catching other people out as well. 
For now I will close this issue since once we fix this in the API it should resolve the SDK issue, if not then we can re-open this issue or raise a new one.
Thanks for raising this
