### ISSUE TITLE
Deleting Custom Attributes

### ISSUE THREAD

**Issue by stajics** [intercom/intercom-node#144]
Is there a way to update the user and delete his custom attribute? I can set each attribute to null but can't figure out how to remove it from custom attributes object.

**Comment by poberherr** [comment]
I am also interested in that. I integrated it with segment and literally a few hundred custom attribute fields got created. I'd need the following functionality:
* get all existing custom attributes
* CRUD for custom attributes basically over api

**Comment by andreffs18** [comment]
Hey! 
Also wondering how can we remove **custom_attributes** from users.

**Comment by choran** [comment]
Hi All, 
Unfortunately this is not possible at the moment.
You can archive them via the UI so that they do not appear in the list as [described here](https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-intercom-to-be-about-your-users/send-custom-user-attributes-to-intercom)
But it is not possible to delete them.
We are looking into this at the moment to see if we can add this functionality but it is not a restriction of the SDK at the moment, rather a general restriction. If the functionality is added to the API we can look at adding it to the SDKs.
In the meantime we will track this internally as a product feature, i.e. being able to delete custom attributes.
So I will close this for now since it is a feature we are tracking internally. But please feel free to reopen if you think it should be an open issue in SDK also
thanks
Cathal

**Comment by svassaux** [comment]
Have you worked on this? Woule be nice to clean up our intercom and remove old fields. Imagine when someones makes a spelling error,, we still have to keep the attribute

**Comment by poberherr** [comment]
Hey sorry - this is a longer outstanding task;
The only thing you can do over the UI is to "archive" fields but not really delete them; or did this change by now?
I remember that I ran into that problem and had no way of "cleaning up" the account, except writing support and beeing migrated to a bigger cluster or "creating a new account".

**Comment by MahanteshAngadiGH** [comment]
Hi,
I have also ran into the same issue. I would like remove few attributes due to spelling mistake & non standard naming convention and recreate them properly.
Is there a solution on this by this time?
Regards,
Mahantesh

**Comment by poberherr** [comment]
2nd that. An update would be cool.

TBH there seems to be not a lot development on those issues. Eventually they had to move me to different cluster with higher attribute counts since a script bloatet attributes in my intercom instance.
Kinda disappointing

**Comment by guillaumemeyer** [comment]
+1... very disappointing not beeing able to clean db...

**Comment by DivyanshBatham** [comment]
Intercom, Why is this feature so hard to implement? I need to be able to edit the custom attribute name, for consistency.

**Comment by WillCooter** [comment]
Using the api, if you set a custom attribute to an empty string then it will be set to `unknown`. This works for fields of any type

```ts
const clearCustomAttribute = async () => {
    return intercom_client.users.update({
            user_id: user_id.toString(),
            custom_attributes: {
                numeric_value: '',
                string_value: '',
            },
    })
}
```

**Comment by msalamat** [comment]
at this rate I will be married before this ever gets implemented

**Comment by arthureichelberger** [comment]
Adding my stone to the building. 🫣

**Comment by melosch** [comment]
I have just taken the time to sign up to express that we are still disappointed in 2024.

**Comment by pedro380085** [comment]
Why is this so difficult to implement? There so much garbage we want to delete.

**Comment by kingbeto** [comment]
Get this done for Christ sake.

**Comment by endasil** [comment]
Since intercom has abandoned development, is what are some good alternatives?
