### ISSUE TITLE
User tagging does not work with email or user_id

### ISSUE THREAD

**Issue by tyrw** [intercom/intercom-node#148]
## Version info
  - intercom-node version: 2.8.7
  - Node version: 6.9

## Expected behavior
Node SDK is a wrapper for API, such that `client.tags.tag` works for user model with `id`, `email`, or `user_id` as described in the [API docs for user tagging](https://developers.intercom.com/v2.0/reference#tag-or-untag-users-companies-leads-contacts)

## Actual behavior
`client.tags.tag` only works with `id`

## Steps to reproduce
```
client.tags.tag({
  name: 'Testing',
  users: [{ email: 'existing-email@example.com' }]
}, callback)
```

## Logs
```
{ type: 'error.list',
  request_id: 'ar96rsta8scuh9f0m0bg',
  errors: [ { code: 'not_found', message: 'User Not Found' } ] }
```

**Comment by Skaelv** [comment]
Hi @tyrw.
I just tried to reproduce and I was able to tag an existing user using the following:
```javascript
client.tags.tag({name: 'Testing', users: [{ email: 'test_dx_3@example.com' }]}, function(res) {console.log(res)});
``` 

![image](https://cloud.githubusercontent.com/assets/5072452/26828571/06b018c0-4aba-11e7-8d86-049d9c3c392d.png)

I don't think anything changed in how we tag users in this lib since you reported the issue. 

It is very strange that it didn't work for you if you are 100% confident the user exists.

Could you retry with another user and let me know if that works?

**Comment by Skaelv** [comment]
I'll close now please re-open if it still fails for you.
