### ISSUE TITLE
Promise not properly returned

### ISSUE THREAD

**Issue by rubenstolk** [intercom/intercom-node#156]
Warning: a promise was created in a handler at `node_modules/intercom-client/dist/scroll.js:50:18` but was not returned from it, see http://goo.gl/rRqMUw

**Comment by choran** [comment]
Hi @rubenstolk 
Did you get an error when using the scroll? I just wanted to see if you were also experiencing any errors with scroll or was it just the warning at the moment?
I will need to look at the code in a bit more detail to see where else we should be returning from. I was looking through the linked note on this behaviour so will try and match that with the code and see where else we should be returning.
Thanks
Cathal

**Comment by choran** [comment]
Hi @rubenstolk 
Are you still seeing this issue?
I was not able to pinpoint the issue here. If you can provide more context then please re-open this and would be happy to look into it.
I know we do have some issues with callbacks/promises.
For example we had a general issues with error handling which was addressed by this PR #191 
So we do need to try and address these but just wasnt 100% sure what the issue was here.
Thanks and feel free to re-open
Cathal
