### ISSUE TITLE
Can't delete companies

### ISSUE THREAD

**Issue by nickhaughton** [intercom/intercom-node#157]
## Version info
  - intercom-node version: 2.8.8
  - Node version: N/A

## Expected behavior
Being able to delete companies

## Actual behavior
Can't delete companies

**Comment by choran** [comment]
Hi @nickhaughton 
Thanks for raising this. 
Unfortunately, you cannot delete a company via the API at the moment as noted [here](https://developers.intercom.com/reference#delete-a-company). 
But as you noted this is definitely something that make sense and should be added to the API. So at the moment it is not an issue with the SDKs as such since it is not allowed functionality in the API.
As a result for these issues we track them internally so that we can plan for API/product updates instead of leaving it as a open issue for the SDK at the moment.
thanks again
Cathal
