### ISSUE TITLE
Bulk create for tags

### ISSUE THREAD

**Issue by Kinaan** [intercom/intercom-node#158]
This is not a bug, more like a question that can lead to enhancement. 

Currently I can't find a way/method in which we can tag a user or company except by calling create method on `client.tags` object. So whenever we have to update a user/company with lets say 10 tags, we have to call `client.tags.create` methods 10 times with associated company/user object.   

My question is that there is a `bulk` method available for users, do you have any plans to introduce same for tags ? Also does the intercom api support bulk creation of tags ?

**Comment by choran** [comment]
Hi @Kinaan 
Thanks for raising this. 
I just want to clarify that I understand your request, you can tag multiple users with the same tag with one request. But I think your are asking for the ability to be able to tag one user with multiple different tags instead? 
So the API does support bulk tagging of users by allowing you to tag a list of leads/users in one request.
But it does not support tagging one user with multiple tags. I just had to double check this myself since I had not thought about that use case, i.e. same user with multiple different tags but it does not seem possible on the API
Let me know if I have understood this correctly. If it is something that is not supported via the API then I usually close the issues in the SDK and instead track it internally since it is something that needs to be added to the API or the product first before we can then add them to the SDK
Thanks
Cathal

**Comment by Kinaan** [comment]
@choran . Yes you understood it perfectly. The use case is that of tagging a single user/company with multiple tags.

**Comment by choran** [comment]
Hi @Kinaan 
Thanks for the update. Since this is currently not possibly via the API I will track it internally as a feature request for the API and close the issue here with the SDK for now.
Thanks for clrifying
Cathal

**Comment by lucasprag** [comment]
Hi @choran Any news on this feature?

**Comment by tanogalego** [comment]
Hey @choran Any news about this ??

**Comment by octisfall** [comment]
Hi @choran. Any news?

**Comment by choran** [comment]
Hi All, 
Unfortunately, this is still not possible via the API. We were reviewing our tagging features via the API recently and did some work on conversation tagging to make it easier to retrieve all the tags for a conversation. But we didnt get to make any changes relating to this particular feature so it is still not possible. 

We are also looking at how best to support general bulk operations in the future, this is an area we have been planning to do some investigations in for a while now. We could cover actions like this in a bulk type operations like that mentioned earlier. We could also provide some feature in the bulk API itself. So we are not 100% sure yet which approach makes the best sense. This is partly one of the delays with this feature.

Thanks for your patience here, and for the updated requests. The fact that there are a number of requests on this issue means that it is something that would be useful for alot of people so this is helpful for planning/prioritizing. I will ensure that I provide a update on this shortly after a bit more digging.

Cheers
Cathal
