### ISSUE TITLE
Access Tokens do not work?

### ISSUE THREAD

**Issue by kopertop** [intercom/intercom-node#160]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-node version: 2.8.8
  - Node version: 6.11.0

## Expected behavior

User should be created when using Access Tokens
```
      var intercomClient = new Intercom.Client({ token: <ACCESS-TOKEN> });
      intercomClient.users.create(data);
```

## Actual behavior

Response is a 401, indicating the Authorization failed using *Basic <hashed key>*

The API guide suggests this should be a *Bearer* authorization request, not a *Basic* Authorization request.

## Steps to reproduce
 1. Create an Access Token on the Developer Portal
 2. Initialize the Intercom Client using the above steps
 3. Try to perform any action (such as creating a user)

## Logs
```
{
  "statusCode": 401,
  "body": {
    "type": "error.list",
    "request_id": "XXX",
    "errors": [
      {
        "code": "token_not_found",
        "message": "Unauthorized"
      }
    ]
  },
  "headers": {
    "cache-control": "no-cache",
    "content-type": "application/json; charset=utf-8",
    "date": "Thu, 10 Aug 2017 15:25:43 GMT",
    "server": "nginx",
    "set-cookie": [
      "_mkra_ctxt=XXX--401; path=/; max-age=5; HttpOnly; secure"
    ],
    "status": "401 Unauthorized",
    "strict-transport-security": "max-age=31557600; includeSubDomains; preload",
    "vary": "Accept-Encoding",
    "www-authenticate": "Basic realm=\"intercom.io\"",
    "x-content-type-options": "nosniff",
    "x-frame-options": "SAMEORIGIN",
    "x-intercom-version": "0f64d9119c6ecfdd4f3f82a86ee4733ae3911fa3",
    "x-ratelimit-limit": "500",
    "x-ratelimit-remaining": "500",
    "x-ratelimit-reset": "1502378760",
    "x-request-id": "XXX",
    "x-runtime": "0.015516",
    "x-xss-protection": "1; mode=block",
    "transfer-encoding": "chunked",
    "connection": "Close"
  },
  "request": {
    "uri": {
      "protocol": "https:",
      "slashes": true,
      "auth": null,
      "host": "api.intercom.io",
      "port": 443,
      "hostname": "api.intercom.io",
      "hash": null,
      "search": null,
      "query": null,
      "pathname": "/events",
      "path": "/events",
      "href": "https://api.intercom.io/events"
    },
    "method": "post",
    "headers": {
      "Content-Type": "application/json",
      "Accept": "application/json",
      "User-Agent": "intercom-node-client/2.0.0",
      "authorization": "Basic <HASHED-TOKEN>",
      "content-length": 92
    }
  }
}
```

**Comment by heymartinadams** [comment]
Same here. Receiving error: `Could not construct a client with those parameters` when using this code:
```
const client = new Intercom.Client({ token: process.env.REACT_APP_INTERCOM_TOKEN })
```

**Comment by kopertop** [comment]
My issue turned out to be that Intercom changed the API token on me without me realizing it.... (I had requested extended scopes, and somehow this ended up with new API tokens).

Still, it shouldn't be sending this as "Basic" authentication token, it should be using "Bearer". I think this is a "it works" type of scenario for the API, but it's not the way it's documented in the API.

**Comment by heymartinadams** [comment]
If it’s already resolved, can you close this issue @kopertop?

**Comment by choran** [comment]
Hi @kopertop 
Glad to head you got it working.
Yeah, fair point we should use the bearer header auth as specified in the API. It was confusing customers with the basic auth so we added a wrapper here to help alleviate that issue as quickly and easily as possible. We could update it so it uses bearer behind the scenes.
But for now I will close this issue since you confirmed that the client init does work correctly.
But feel free to re-open this or open another issue if you would like to add more info or feel that it should not be closed.
Thanks again
Cathal

**Comment by wlodi83** [comment]
Hi, I have exactly the same problem. I am using env variable for token.

Version:
"intercom-client": "2.8.8"
node: v4.8.3

I construct client with following:

var client = new Intercom.Client({ token: process.env.INTERCOM_TOKEN });

**Comment by heymartinadams** [comment]
@wlodi83 Just updated my comment with a working server-side and client-side example.

**Comment by choran** [comment]
Thanks for updating your comments @heymartinadams 
The documentation is updated to show how to use the access tokens. When you note that "The documentation here is sketchy IMO" what type of fully worked example would you think is helpful here? Similar to the one you provided in your comments? 
Was just wondering where you think the confusion is arising from here.
Thanks again
Cathal

**Comment by heymartinadams** [comment]
@choran, yes, it was not clear to me from the docs what needed to be done in terms of ID verification and then also on the client-side and how they should talk to each other. I checked both [here](https://developers.intercom.com/docs/cordova-phonegap-identity-verification) and [here](https://gist.github.com/thewheat/7342c76ade46e7322c3e).

I am a junior dev, so that needs to be kept in mind. At the same time, if you can write docs in a way that junior devs can “get it”, you can be sure they are good. I think the more examples you include also, the better. Another case was that custom variables are differently displayed for Cordova and web apps, which was not clear from the docs.

I put together a comprehensive example for both the client and server (for other people to see) here: https://github.com/graphcool-examples/functions/tree/a27b7f00f2b0b2865c4a010a2c8fe8684af6fd2f/miscellaneous/intercom
