### ISSUE TITLE
Security advisory in dependency

### ISSUE THREAD

**Issue by newyorkpizza** [intercom/intercom-node#163]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-node version: 2.8.9
  - Node version: all

## Expected behavior
That the Intercom SDK does not depend on library versions with known vulnerabilities/advisories.

## Actual behavior
This library indirectly depends on mime@1.3.6:
`intercom-client > unirest@0.5.1 > mime@1.3.6`

There is an open advisory against mime@1.3.6: https://nodesecurity.io/advisories/535.

I've logged an issue with `unirest` (https://github.com/Mashape/unirest-nodejs/issues/111) but the maintainers have not updated their library.

Perhaps Intercom should fork `unirest` in order to use an updated version of `mime` until `unirest` pushes a new version?

**Comment by choran** [comment]
@newyorkpizza thanks for highlighting this. Ideally we would not like to fork any code such as this since it tends to create more issues down the line. I would like if the changes were made in the main repo but like you said it looks like there is no update there. 
For the time begin we will leave this open track this and can revisit if there are no updates from the issue you opened.
Thanks again for raising this

**Comment by newyorkpizza** [comment]
Thanks @choran and @mckenna !
