### ISSUE TITLE
How to find all users with a certain email?

### ISSUE THREAD

**Issue by Jolg42** [intercom/intercom-node#167]
Hi,
When using the `ic.users.find or ic.users.listBy` it returns `Multiple existing users match this email address ...` sometimes.
The expected behavior for me is too have a function that can return the list of multiples. Is that doable?
This is a big issue right now because when processing I need to handle these manually as I can't script it.

**Comment by choran** [comment]
Hi @Jolg42 
Unfortunately, this is currently a restriction on our API and the the SDK.
You can find more information on it in this issue #155 

You can list for multiple leads using listby but at present you will receive the above error when listing users by email when multiple emails are found.

As noted in the related issue it is something we are aware of and are looking into since it has been requested by other customers.

Cheers
Cathal

**Comment by Jolg42** [comment]
Hi @choran 
Indeed this is a limitation and processing these exceptions are time consuming right now.
Thanks for the update, keep us updated when it's ready ;)

**Comment by choran** [comment]
np @Jolg42, will do.
I will close this right now, since this is an API issue and not related to the SDK. 
When we have an update on this we will announce it on the [Intercom developers blog](https://developerblog.intercom.com/)
Cheers
Cathal

**Comment by jaGarcia** [comment]
+1 patching/supporting this in the API would be nice.. failing in this scenario seems aggressive.

**Comment by rogerkerse** [comment]
+1

**Comment by waqasraza123** [comment]
this is a needed feature

**Comment by hexsprite** [comment]
+1 need this... the alternative is I guess listing all users and processing it on the client side?
