### ISSUE TITLE
Bulk update support?

### ISSUE THREAD

**Issue by kevzettler** [intercom/intercom-node#205]
Does this module support bulk updates? looks like the python library has special methods for that

**Comment by jonnyom** [comment]
Hi @kevzettler thanks for reaching out, sorry for the delay in getting back to you.

Short answer: no, they aren't supported. 

Bulk endpoints aren't currently supported as they aren't in a good state right now and need additional work.

The Python library isn't actually an official library, but was built by a third party. We now have it under our organisation as the third party was not able to continue hosting it. However, we aren't actively working on it - and if we do release a Python SDK we will more than likely write our own new one, to match the current state of the product.

I'm going to close this out now as it isn't an issue, but happy to answer any questions you might have 😄

**Comment by imjared** [comment]
@jonnyom Does "they need additional work" mean that anyone at intercom is working on this? It's really strange to have to go through tens of thousands of users one-by-one to make updates.

I'm sure you all are aware that this is a [pain point for developers](https://github.com/intercom/intercom-ruby/issues?utf8=%E2%9C%93&q=is%3Aissue+bulk) but the only information that seems to be available is basically your response above of "we need to rethink this".

**Comment by jonnyom** [comment]
@imjared we have work lined up to tackle the issue, but I can't give a timeline of how long that will take or anything more than that.

The bulk APIs as they were weren't very well thought out, and the only benefit they actually gave was that you could shorten the number of jobs. Each update per user counted towards the rate limit, so you wouldn't see a benefit there.

If a bulk job failed, we only returned that the whole thing failed, rather than what caused the failure.

Additionally, we still only processed the updates incrementally, so you wouldn't see a performance benefit to it!

Because of these we weren't comfortable continuing with the bulk APIs and need to rethink how we want to do large-scale user updates over the API to make it a more usable interface.

As I said, I can't give a timeline on this work, but it's something we're well aware of and are working towards a usable solution.

**Comment by kylehotchkiss** [comment]
I'm working on an application with 100k+ users and frequently need to run updates that change data across all users. CSV imports are somewhat clunky, especially if we need to update every users attribute nightly with something from our database.

I've seen "use the bulk update api" as a response in old Intercom Github tickets several times and it feels like a step backwards to have to run every contact update as its own API request. Please have your team consider the bulk API as a higher priority as it would help applications with frequently attribute update needs build more reliable and quick integrations with your platform.

Some other bulk APIs i've been using lately are Firebase's Firestore Database batch write (500 records at a time) and Sendgrid's batch contact update (1000 contacts at a time). Both of these APIs help us create reliable integrations where there's a bit of data moving between platforms on a regular basis.
