### ISSUE TITLE
How can I get the conversation id?

### ISSUE THREAD

**Issue by illyavorobets** [intercom/intercom-node#262]
Version info
intercom-node version: 2.8.6
Node version: 4.3.1
Expected behavior
After creating and admin or user initiated conversation it would be great to reply to it.

Actual behavior
After creating the admin or user initiated conversation if you try to reply to it providing the conversation id, it's not working.

The id of the conversation does not match the id that I can see in the messages inbox... so it looks like the conversation id is not provided...!

Steps to reproduce
Create an admin or user initiated conversation
Reply to it providing the id from last request
Logs
body.errors [{"code":"not_found","message":"Resource Not Found"}]

Workaround
I found that I can pass id: 'last' and it works but it's more an hack...! (Library code enabling that and doc for last reply)

**Comment by lloydliyu** [comment]
Hey @illyavorobets :wave:

This is actually an expected behaviour of the API and nothing to do with the SDK itself. The API returns a message object as the conversation would be created later on. With versions 1.x of our API, you can list conversations for the specific user, and check if the message id is contained in any of those conversations matches. 

If you have any further questions on this, or would like to log this as a feature request with the team, I'd recommend reaching out to the support team using the Messenger at https://intercom.com.

Closing this out as this isn't an issue with the SDK itself.
