### ISSUE TITLE
When tagging multiple users, if one of them does not exist in Intercom, tagging fails for all of them

### ISSUE THREAD

**Issue by LaureRC** [intercom/intercom-node#263]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-node version: 2.10.5
  - Node version: 12.7.0

## Expected behavior

Let's consider this call, where "userMail@mail.com" and "userMail2@mail.com" are the emails of users already existing in Intercom, whereas "notUserMail@mail.com" is an email which is not linked to any user : 
```
client.tags.tag({ name: 'tagName', users: [{ email: 'userMail@mail.com' }, { email: 'userMail2@mail.com' }, {email: 'notUserMail@email.com'] });
```
I expected that the users existing in Intercom will be properly tagged, and that an error will be returned saying that no user could be found with the email "notUserMail@email.com".

## Actual behavior
An error is returned, but no user is tagged. Furthermore, I don't know which one has raised the error as the error message is `[ { code: 'not_found', message: 'User Not Found' } ]`

## Steps to reproduce
 1. Create a user in Intercom with the email "firstEmail@mail.com"
 2. Run `client.tags.tag({ name: 'tagName', users: [{ email: 'firstEmail@mail.com' }, {email: 'secondEmail@email.com'] });`
 3. An error is returned "User Not Found" (but no indication on which one), and none of the two users is tagged.

## Logs
Body of the error returned : 
```
{
   type: 'error.list',
   request_id: '000c0e20ni1jpf0vnpog',
   errors: [ { code: 'not_found', message: 'User Not Found' } ]
}
```

**Comment by lloydliyu** [comment]
Hey @LaureRC :wave:

This issue is actually being raised by the API itself and not the SDK. To my knowledge this is actually expected behaviour of the REST API to validate the full set and throw an error if any of the included users appears incorrect. If you haven't already and are still running into this as an issue, I'd recommend reaching our to the support team using the Messenger at https://intercom.com who can log this as a feature request and potentially give guidance on workarounds if any exist.

Closing this out as it isn't an issue with the SDK itself.
