### ISSUE TITLE
Internal node error when sending a message

### ISSUE THREAD

**Issue by cwhenderson20** [intercom/intercom-node#79]
I've encountered a strange error when using the library to send messages. I'll do my best to describe the issue, but my use case is quite particular.

I am using node's cluster module and the Intercom message is being sent via a child process and is also wrapped inside a try/catch block to ensure no uncaught errors cause the child process to crash. The Intercom message was the last call in the async chain, but it appears that it was never able to successfully call its callback as this internal node error appears in the logs:

```
nodejs: ../src/util-inl.h:196: TypeName* node::Unwrap(v8::Local<v8::Object>) [with TypeName = node::crypto::SecureContext]: Assertion `(object->InternalFieldCount()) > (0)' failed.
```

Logging the exit code and signal of the forked process (via the master process' `on.("exit", ...)` event) shows that it exits with code `null` and signal `SIGABRT`. 

Removing the Intercom message method stops the internal node error from appearing, the final callback is called, and the process exits with no errors. For now, I have replaced the library with a simple HTTP request via the request library and everything works correctly. 

For reference, this was running on Ubuntu 14.04, Docker 1.10.2, Node v4.3.0.

I apologize if any of this is vague. Please ask for whatever details you may in order to look into this and I'll be happy to clarify.

**Comment by choran** [comment]
Hi @cwhenderson20, I just first wanted to check that you are still encountering this issue or were you able to resolve it? 
I was trying to reproduce this but, as you noted, your use case is particular. Is there any example code you can provide so that I can try and re-create this and ensure that I am following similar steps? 

Were you able to configure it so that you could send a simple msg? i.e. you said you were able to workaround this by using a simple HTTP request, but I just wanted to check that you were able to use the Intercom library to send a simply msg as we describe in the README?  I am not sure what may be causing this at the moment, but if you can provide any example code I may be able to try and re-create it.

**Comment by Skaelv** [comment]
I'm closing as this seems out of date .Re-open if you are still seeing this issue.
