### ISSUE TITLE
Multiple existing users match this email address Error

### ISSUE THREAD

**Issue by foobar8675** [intercom/intercom-node#96]
i have a segment like the following code snippet which finds a user by their email and sends an intercom message using the api. the issue is sometimes i get an error like the following. 

````
{"statusCode":400,"body":{"type":"error.list","request_id":"almvmvb7hnr3hjonq670","errors":[{"code":"conflict","message":"Multiple existing users match this email address XXX@gmail.com - must be more specific using user_id"}]}
````

I'm pretty sure this is because this email exists twice in intercom, since we were, for a while, using the same intercom app for both our dev and prod ios apps.

so my first question is in this case it possible to return a list of users , maybe using `listBy` instead of just throwing an error when this case happens?

````
    client.users.find({ email: req.user.email })
     .then(function (r) {
      var message = {
        message_type: 'inapp',
        subject: subject,
        body: msg,
        template: 'plain',
        from: {
          type: 'admin',
          id: process.env.INTERCOM_FROM_ACCOUNT,
        },
        to: {
          type: 'user',
          user_id: r.body.user_id,
        },
      };
      return client.messages.create(message);
    }).then(function (r) {
      return res.status(200).json({ success: true, message: helper.strings.MessageSent });
    }).catch(function (e) {
      helper.logging.logError(e, req);
      res.status(500).json({ success: false, message: helper.strings.AnErrorHappened });
    });
````

secondly, this might be more an iOS question, but I dont even see a way to get the user id from the API to pass it to the server.

Anyways, any suggestions are appreciated.

**Comment by bobjflong** [comment]
Hi @foobar8675 

You're correct - when you try to identify a single user, using an identifier that matches multiple users, the API will return an error. This is because the API does not know which user to respond with. The signature of `find` is always to return a single result, so I'm not sure if turning it into a list is something we should do.

> secondly, this might be more an iOS question, but I dont even see a way to get the user id from the API to pass it to the server.

Are you referring to the user_id? This is an id that you set, and it is unique per user. It is documented [here](https://developers.intercom.io/reference#create-or-update-user).

**Comment by foobar8675** [comment]
that worked great. thanks.
